[project]
name = "dviz-project"
version = "0.1.0"
description = "Final Project for HSLU DVIZ HS24 Class"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.4.1",
    "pandas>=2.2.3",
    "streamlit>=1.39.0",
]

